# Generated by Django 5.2.5 on 2025-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
